2020-11-23 14:06:32,100 INFO    MainThread:38103 [wandb_setup.py:_flush():70] setting env: {}
2020-11-23 14:06:32,100 INFO    MainThread:38103 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2020-11-23 14:06:32,100 INFO    MainThread:38103 [wandb_setup.py:_flush():70] setting login settings: {}
2020-11-23 14:06:32,100 INFO    MainThread:38103 [wandb_setup.py:_flush():70] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f6a680600d0>
2020-11-23 14:06:32,100 INFO    MainThread:38103 [wandb_init.py:_log_setup():303] Logging user logs to /home/namitrak/Documents/Machine Learning/Image segmentation/wandb/run-20201123_140632-8ut6mne3/logs/debug.log
2020-11-23 14:06:32,100 INFO    MainThread:38103 [wandb_init.py:_log_setup():304] Logging internal logs to /home/namitrak/Documents/Machine Learning/Image segmentation/wandb/run-20201123_140632-8ut6mne3/logs/debug-internal.log
2020-11-23 14:06:32,799 INFO    MainThread:38103 [wandb_run.py:_console_start():1218] atexit reg
2020-11-23 14:06:32,799 INFO    MainThread:38103 [wandb_run.py:_redirect():1085] redirect: SettingsConsole.WRAP
2020-11-23 14:06:32,800 INFO    MainThread:38103 [wandb_run.py:_redirect():1116] Wrapping output streams.
2020-11-23 14:06:32,800 INFO    MainThread:38103 [wandb_run.py:_redirect():1132] Redirects installed.
2020-11-23 14:06:35,252 INFO    MainThread:38103 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 14:06:35,257 INFO    MainThread:38103 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 14:06:58,607 INFO    MainThread:38103 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 14:06:58,611 INFO    MainThread:38103 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 14:06:58,752 INFO    MainThread:38103 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 14:06:58,759 INFO    MainThread:38103 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 14:06:58,760 INFO    MainThread:38103 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 14:06:58,764 INFO    MainThread:38103 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 14:06:58,990 INFO    MainThread:38103 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 14:06:58,994 INFO    MainThread:38103 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 14:06:59,193 INFO    MainThread:38103 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 14:06:59,196 INFO    MainThread:38103 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 14:06:59,423 INFO    MainThread:38103 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 14:06:59,426 INFO    MainThread:38103 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 14:07:00,768 INFO    MainThread:38103 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 14:07:00,776 INFO    MainThread:38103 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 14:07:01,921 INFO    MainThread:38103 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 14:07:35,548 INFO    MainThread:38103 [wandb_run.py:_atexit_cleanup():1188] got exitcode: 0
2020-11-23 14:07:35,548 INFO    MainThread:38103 [wandb_run.py:_restore():1160] restore
2020-11-23 14:07:35,551 INFO    MainThread:38103 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "26393afa11df4f65b70425719a5cb93d"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 621
      total_bytes: 621
    }
  }
}

2020-11-23 14:07:37,555 INFO    MainThread:38103 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "13885407b1b843fb8903c709ab5d09b3"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 4420
      total_bytes: 4420
    }
  }
}

2020-11-23 14:07:38,626 INFO    MainThread:38103 [wandb_run.py:_show_files():1517] logging synced files
2020-11-23 14:07:38,709 INFO    MainThread:38103 [internal.py:handle_exit():138] Internal process exited
