cuda
2975 2975
(4, 256, 256, 1)
torch.Size([3, 256, 256]) torch.Size([1, 256, 256])
torch.Size([3, 256, 256]) torch.Size([1, 256, 256])
torch.Size([3, 256, 256]) torch.Size([1, 256, 256])
torch.Size([3, 256, 256]) torch.Size([1, 256, 256])
torch.Size([3, 256, 256]) torch.Size([1, 256, 256])
torch.Size([3, 256, 256]) torch.Size([1, 256, 256])
0 torch.Size([5, 3, 256, 256]) torch.Size([5, 1, 256, 256])
1 torch.Size([5, 3, 256, 256]) torch.Size([5, 1, 256, 256])
2 torch.Size([5, 3, 256, 256]) torch.Size([5, 1, 256, 256])
3 torch.Size([5, 3, 256, 256]) torch.Size([5, 1, 256, 256])
4 torch.Size([5, 3, 256, 256]) torch.Size([5, 1, 256, 256])
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7ff75265a820>
Traceback (most recent call last):
  File "/home/namitrak/anaconda3/envs/rl_gan/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in __del__
    self._shutdown_workers()
  File "/home/namitrak/anaconda3/envs/rl_gan/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1177, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/home/namitrak/anaconda3/envs/rl_gan/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/namitrak/anaconda3/envs/rl_gan/lib/python3.8/multiprocessing/popen_fork.py", line 44, in wait
    if not wait([self.sentinel], timeout):
  File "/home/namitrak/anaconda3/envs/rl_gan/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/home/namitrak/anaconda3/envs/rl_gan/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt: 
