2020-11-23 17:03:06,478 INFO    MainThread:14200 [wandb_setup.py:_flush():70] setting env: {}
2020-11-23 17:03:06,478 INFO    MainThread:14200 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2020-11-23 17:03:06,478 INFO    MainThread:14200 [wandb_setup.py:_flush():70] setting login settings: {}
2020-11-23 17:03:06,478 INFO    MainThread:14200 [wandb_setup.py:_flush():70] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7feaa371b0a0>
2020-11-23 17:03:06,478 INFO    MainThread:14200 [wandb_init.py:_log_setup():303] Logging user logs to /home/namitrak/Documents/Machine Learning/Image segmentation/wandb/run-20201123_170306-2er3kh7z/logs/debug.log
2020-11-23 17:03:06,478 INFO    MainThread:14200 [wandb_init.py:_log_setup():304] Logging internal logs to /home/namitrak/Documents/Machine Learning/Image segmentation/wandb/run-20201123_170306-2er3kh7z/logs/debug-internal.log
2020-11-23 17:03:07,161 INFO    MainThread:14200 [wandb_run.py:_console_start():1218] atexit reg
2020-11-23 17:03:07,162 INFO    MainThread:14200 [wandb_run.py:_redirect():1085] redirect: SettingsConsole.WRAP
2020-11-23 17:03:07,162 INFO    MainThread:14200 [wandb_run.py:_redirect():1116] Wrapping output streams.
2020-11-23 17:03:07,162 INFO    MainThread:14200 [wandb_run.py:_redirect():1132] Redirects installed.
2020-11-23 17:03:09,607 INFO    MainThread:14200 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 17:03:09,612 INFO    MainThread:14200 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 17:03:33,405 INFO    MainThread:14200 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 17:03:33,410 INFO    MainThread:14200 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 17:03:33,541 INFO    MainThread:14200 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 17:03:33,547 INFO    MainThread:14200 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 17:03:33,548 INFO    MainThread:14200 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 17:03:33,551 INFO    MainThread:14200 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 17:03:33,777 INFO    MainThread:14200 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 17:03:33,781 INFO    MainThread:14200 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 17:03:34,054 INFO    MainThread:14200 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 17:03:34,059 INFO    MainThread:14200 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 17:03:34,286 INFO    MainThread:14200 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 17:03:34,289 INFO    MainThread:14200 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 17:03:35,590 INFO    MainThread:14200 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 17:03:35,596 INFO    MainThread:14200 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 17:03:36,800 INFO    MainThread:14200 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 17:03:55,270 INFO    MainThread:14200 [wandb_run.py:_atexit_cleanup():1188] got exitcode: 0
2020-11-23 17:03:55,271 INFO    MainThread:14200 [wandb_run.py:_restore():1160] restore
2020-11-23 17:03:55,274 INFO    MainThread:14200 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "305b344857a04ae18b61a79f7e662b72"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 621
      total_bytes: 621
    }
  }
}

2020-11-23 17:03:57,282 INFO    MainThread:14200 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "e4abae58134e4be4ac733e599bbed2a4"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 4420
      total_bytes: 4420
    }
  }
}

2020-11-23 17:03:58,354 INFO    MainThread:14200 [wandb_run.py:_show_files():1517] logging synced files
2020-11-23 17:03:58,439 INFO    MainThread:14200 [internal.py:handle_exit():138] Internal process exited
