2020-11-23 13:41:04,688 INFO    MainThread:33361 [wandb_setup.py:_flush():70] setting env: {}
2020-11-23 13:41:04,688 INFO    MainThread:33361 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2020-11-23 13:41:04,688 INFO    MainThread:33361 [wandb_setup.py:_flush():70] setting login settings: {}
2020-11-23 13:41:04,688 INFO    MainThread:33361 [wandb_setup.py:_flush():70] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fd3fd0150d0>
2020-11-23 13:41:04,688 INFO    MainThread:33361 [wandb_init.py:_log_setup():303] Logging user logs to /home/namitrak/Documents/Machine Learning/Image segmentation/wandb/run-20201123_134104-2byi7do4/logs/debug.log
2020-11-23 13:41:04,688 INFO    MainThread:33361 [wandb_init.py:_log_setup():304] Logging internal logs to /home/namitrak/Documents/Machine Learning/Image segmentation/wandb/run-20201123_134104-2byi7do4/logs/debug-internal.log
2020-11-23 13:41:05,309 INFO    MainThread:33361 [wandb_run.py:_console_start():1218] atexit reg
2020-11-23 13:41:05,309 INFO    MainThread:33361 [wandb_run.py:_redirect():1085] redirect: SettingsConsole.WRAP
2020-11-23 13:41:05,310 INFO    MainThread:33361 [wandb_run.py:_redirect():1116] Wrapping output streams.
2020-11-23 13:41:05,310 INFO    MainThread:33361 [wandb_run.py:_redirect():1132] Redirects installed.
2020-11-23 13:41:07,896 INFO    MainThread:33361 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:41:07,900 INFO    MainThread:33361 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:41:33,779 INFO    MainThread:33361 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:41:33,782 INFO    MainThread:33361 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:41:33,911 INFO    MainThread:33361 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:41:33,916 INFO    MainThread:33361 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:41:33,917 INFO    MainThread:33361 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:41:33,919 INFO    MainThread:33361 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:41:34,137 INFO    MainThread:33361 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:41:34,141 INFO    MainThread:33361 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:41:34,314 INFO    MainThread:33361 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:41:34,316 INFO    MainThread:33361 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:41:34,535 INFO    MainThread:33361 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:41:34,538 INFO    MainThread:33361 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:41:35,922 INFO    MainThread:33361 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:41:35,928 INFO    MainThread:33361 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:41:36,970 INFO    MainThread:33361 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:42:15,742 INFO    MainThread:33361 [wandb_run.py:_atexit_cleanup():1188] got exitcode: 0
2020-11-23 13:42:15,742 INFO    MainThread:33361 [wandb_run.py:_restore():1160] restore
2020-11-23 13:42:15,746 INFO    MainThread:33361 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "83c3cb79f4784479b180de64958d8051"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 621
      total_bytes: 621
    }
  }
}

2020-11-23 13:42:17,750 INFO    MainThread:33361 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "bea4aa6df52c4137bca63c756da73821"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 621
      total_bytes: 4428
    }
  }
}

2020-11-23 13:42:18,824 INFO    MainThread:33361 [wandb_run.py:_show_files():1517] logging synced files
2020-11-23 13:42:18,905 INFO    MainThread:33361 [internal.py:handle_exit():138] Internal process exited
