2020-11-23 13:37:24,401 INFO    MainThread:32513 [wandb_setup.py:_flush():70] setting env: {}
2020-11-23 13:37:24,401 INFO    MainThread:32513 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2020-11-23 13:37:24,401 INFO    MainThread:32513 [wandb_setup.py:_flush():70] setting login settings: {}
2020-11-23 13:37:24,401 INFO    MainThread:32513 [wandb_setup.py:_flush():70] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fd9048420d0>
2020-11-23 13:37:24,402 INFO    MainThread:32513 [wandb_init.py:_log_setup():303] Logging user logs to /home/namitrak/Documents/Machine Learning/Image segmentation/wandb/run-20201123_133724-3fzhp96k/logs/debug.log
2020-11-23 13:37:24,402 INFO    MainThread:32513 [wandb_init.py:_log_setup():304] Logging internal logs to /home/namitrak/Documents/Machine Learning/Image segmentation/wandb/run-20201123_133724-3fzhp96k/logs/debug-internal.log
2020-11-23 13:37:25,141 INFO    MainThread:32513 [wandb_run.py:_console_start():1218] atexit reg
2020-11-23 13:37:25,142 INFO    MainThread:32513 [wandb_run.py:_redirect():1085] redirect: SettingsConsole.WRAP
2020-11-23 13:37:25,142 INFO    MainThread:32513 [wandb_run.py:_redirect():1116] Wrapping output streams.
2020-11-23 13:37:25,142 INFO    MainThread:32513 [wandb_run.py:_redirect():1132] Redirects installed.
2020-11-23 13:37:27,598 INFO    MainThread:32513 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:37:27,602 INFO    MainThread:32513 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:37:52,994 INFO    MainThread:32513 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:37:52,997 INFO    MainThread:32513 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:37:53,130 INFO    MainThread:32513 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:37:53,136 INFO    MainThread:32513 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:37:53,137 INFO    MainThread:32513 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:37:53,140 INFO    MainThread:32513 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:37:53,357 INFO    MainThread:32513 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:37:53,361 INFO    MainThread:32513 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:37:53,753 INFO    MainThread:32513 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:37:53,757 INFO    MainThread:32513 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:37:53,990 INFO    MainThread:32513 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:37:53,993 INFO    MainThread:32513 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:37:55,390 INFO    MainThread:32513 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:37:55,396 INFO    MainThread:32513 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:37:56,795 INFO    MainThread:32513 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:38:31,244 INFO    MainThread:32513 [wandb_run.py:_atexit_cleanup():1188] got exitcode: 0
2020-11-23 13:38:31,244 INFO    MainThread:32513 [wandb_run.py:_restore():1160] restore
2020-11-23 13:38:31,247 INFO    MainThread:32513 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "87ea33c136da4bd8b54c400b48872690"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 621
      total_bytes: 621
    }
  }
}

2020-11-23 13:38:33,249 INFO    MainThread:32513 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "8a106a4c1b2048128e1447be188c93f5"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 4428
      total_bytes: 4428
    }
  }
}

2020-11-23 13:38:34,321 INFO    MainThread:32513 [wandb_run.py:_show_files():1517] logging synced files
2020-11-23 13:38:34,414 INFO    MainThread:32513 [internal.py:handle_exit():138] Internal process exited
