2020-11-23 13:42:21,039 INFO    MainThread:33634 [wandb_setup.py:_flush():70] setting env: {}
2020-11-23 13:42:21,039 INFO    MainThread:33634 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2020-11-23 13:42:21,039 INFO    MainThread:33634 [wandb_setup.py:_flush():70] setting login settings: {}
2020-11-23 13:42:21,039 INFO    MainThread:33634 [wandb_setup.py:_flush():70] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f46559750d0>
2020-11-23 13:42:21,039 INFO    MainThread:33634 [wandb_init.py:_log_setup():303] Logging user logs to /home/namitrak/Documents/Machine Learning/Image segmentation/wandb/run-20201123_134221-b6xpdkzj/logs/debug.log
2020-11-23 13:42:21,039 INFO    MainThread:33634 [wandb_init.py:_log_setup():304] Logging internal logs to /home/namitrak/Documents/Machine Learning/Image segmentation/wandb/run-20201123_134221-b6xpdkzj/logs/debug-internal.log
2020-11-23 13:42:21,690 INFO    MainThread:33634 [wandb_run.py:_console_start():1218] atexit reg
2020-11-23 13:42:21,691 INFO    MainThread:33634 [wandb_run.py:_redirect():1085] redirect: SettingsConsole.WRAP
2020-11-23 13:42:21,691 INFO    MainThread:33634 [wandb_run.py:_redirect():1116] Wrapping output streams.
2020-11-23 13:42:21,691 INFO    MainThread:33634 [wandb_run.py:_redirect():1132] Redirects installed.
2020-11-23 13:42:24,255 INFO    MainThread:33634 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:42:24,259 INFO    MainThread:33634 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:42:48,437 INFO    MainThread:33634 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:42:48,440 INFO    MainThread:33634 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:42:48,565 INFO    MainThread:33634 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:42:48,570 INFO    MainThread:33634 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:42:48,571 INFO    MainThread:33634 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:42:48,574 INFO    MainThread:33634 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:42:48,796 INFO    MainThread:33634 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:42:48,800 INFO    MainThread:33634 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:42:48,826 INFO    MainThread:33634 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:42:48,829 INFO    MainThread:33634 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:42:49,053 INFO    MainThread:33634 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:42:49,056 INFO    MainThread:33634 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:42:50,368 INFO    MainThread:33634 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:42:50,375 INFO    MainThread:33634 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:42:51,248 INFO    MainThread:33634 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:43:33,646 INFO    MainThread:33634 [wandb_run.py:_atexit_cleanup():1188] got exitcode: 0
2020-11-23 13:43:33,646 INFO    MainThread:33634 [wandb_run.py:_restore():1160] restore
2020-11-23 13:43:33,650 INFO    MainThread:33634 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "bab5fcfab5c24ebd8cfa9710aab38cc6"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 621
      total_bytes: 621
    }
  }
}

2020-11-23 13:43:35,653 INFO    MainThread:33634 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "7bf237afb8604104af08ceb2d961575f"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 4428
      total_bytes: 4428
    }
  }
}

2020-11-23 13:43:36,725 INFO    MainThread:33634 [wandb_run.py:_show_files():1517] logging synced files
2020-11-23 13:43:36,727 INFO    MainThread:33634 [internal.py:handle_exit():138] Internal process exited
