2020-11-23 13:45:10,186 INFO    MainThread:34146 [wandb_setup.py:_flush():70] setting env: {}
2020-11-23 13:45:10,186 INFO    MainThread:34146 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2020-11-23 13:45:10,186 INFO    MainThread:34146 [wandb_setup.py:_flush():70] setting login settings: {}
2020-11-23 13:45:10,186 INFO    MainThread:34146 [wandb_setup.py:_flush():70] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f86d381e0d0>
2020-11-23 13:45:10,186 INFO    MainThread:34146 [wandb_init.py:_log_setup():303] Logging user logs to /home/namitrak/Documents/Machine Learning/Image segmentation/wandb/run-20201123_134510-1iij69oi/logs/debug.log
2020-11-23 13:45:10,186 INFO    MainThread:34146 [wandb_init.py:_log_setup():304] Logging internal logs to /home/namitrak/Documents/Machine Learning/Image segmentation/wandb/run-20201123_134510-1iij69oi/logs/debug-internal.log
2020-11-23 13:45:10,817 INFO    MainThread:34146 [wandb_run.py:_console_start():1218] atexit reg
2020-11-23 13:45:10,817 INFO    MainThread:34146 [wandb_run.py:_redirect():1085] redirect: SettingsConsole.WRAP
2020-11-23 13:45:10,817 INFO    MainThread:34146 [wandb_run.py:_redirect():1116] Wrapping output streams.
2020-11-23 13:45:10,818 INFO    MainThread:34146 [wandb_run.py:_redirect():1132] Redirects installed.
2020-11-23 13:45:13,272 INFO    MainThread:34146 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:45:13,276 INFO    MainThread:34146 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:45:39,077 INFO    MainThread:34146 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:45:39,081 INFO    MainThread:34146 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:45:39,206 INFO    MainThread:34146 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:45:39,212 INFO    MainThread:34146 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:45:39,213 INFO    MainThread:34146 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:45:39,216 INFO    MainThread:34146 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:45:39,448 INFO    MainThread:34146 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:45:39,451 INFO    MainThread:34146 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:45:39,465 INFO    MainThread:34146 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:45:39,468 INFO    MainThread:34146 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:45:39,709 INFO    MainThread:34146 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:45:39,713 INFO    MainThread:34146 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:45:41,020 INFO    MainThread:34146 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:45:41,026 INFO    MainThread:34146 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 13:45:41,999 INFO    MainThread:34146 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 13:48:03,522 INFO    MainThread:34146 [wandb_run.py:_atexit_cleanup():1188] got exitcode: 0
2020-11-23 13:48:03,523 INFO    MainThread:34146 [wandb_run.py:_restore():1160] restore
2020-11-23 13:48:03,526 INFO    MainThread:34146 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "6bfef1ff20b648e593eca6fb2f3c7619"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 621
      total_bytes: 621
    }
  }
}

2020-11-23 13:48:05,529 INFO    MainThread:34146 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "691c898847cc4ad0a8b169762bd5d8bb"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 4452
      total_bytes: 4452
    }
  }
}

2020-11-23 13:48:06,588 INFO    MainThread:34146 [wandb_run.py:_show_files():1517] logging synced files
2020-11-23 13:48:06,590 INFO    MainThread:34146 [internal.py:handle_exit():138] Internal process exited
